FROM ubuntu
MAINTAINER David Weinstein <david@bitjudo.com>

# install our dependencies and nodejs
RUN echo "deb http://archive.ubuntu.com/ubuntu precise main universe" > /etc/apt/sources.list \
  && apt-get update
  && apt-get -y install python-software-properties git build-essential \
  && add-apt-repository -y ppa:chris-lea/node.js \
  && apt-get update \
  && apt-get -y install nodejs yarn git-core